# Generated by Django 6.0.3 on 2026-04-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ctc',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='gmail_message_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
