# Generated by Django 6.0.3 on 2026-04-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_application_ctc_application_gmail_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
